env:
  browser: true
  es2021: true
extends:
  - plugin:vue/essential
  - standard
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules: {
  'camelcase': 'off',
  'promise/param-names': 'off',
  'vue/multi-word-component-names': 'off',
  'vue/no-reserved-component-names': 'off',
  'vue/require-v-for-key': 'off',
}
