name: Publish Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./sdk
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: sdk/package-lock.json
      - run: npm ci
      - run: chmod +x ./build/test-server/cli.js
      - run: npm link
      - run: npx test-server --launch &
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./sdk
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
          cache-dependency-path: sdk/package-lock.json
      - run: npm ci
      - run: chmod +x ./build/test-server/cli.js
      - run: npm link
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
